name: IPO Scanner

on:
  schedule:
    # Every 5 minutes from 09:30–15:15 IST
    # IST → UTC = 04:00–09:45 UTC

    # 1) 04:00–08:59 UTC → 09:30–14:29 IST
    - cron: "*/5 4-8 * * 1-5"

    # 2) 09:00–09:45 UTC → 14:30–15:15 IST
    - cron: "0-45/5 9 * * 1-5"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore IPO Cache
        uses: actions/cache@v4
        with:
          path: ipo_cache.pkl
          key: ipo-cache-file

      - name: Install dependencies
        run: |
          pip install yfinance pandas requests

      - name: Run IPO Scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python ipo_scanner.py

      - name: Save IPO Cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ipo_cache.pkl
          key: ipo-cache-file